version: '3.8'

services:

  # Web service layer
  server:
    image: 'nginx:stable-alpine'
    container_name: nginx-alpine
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - php
      - mysql

  # Application service Layer
  php:
    container_name: php8
    restart: always
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html
      - ./app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - '9000:9000'
    env_file:
      - ./env/php.env
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql8
    restart: always
    volumes:
      - 'db_data:/var/lib/mysql'
      - './db:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
    env_file:
      - ./env/mysql.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - '81:80'

volumes:
  db_data: